# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
#parameters:
    #parameter_name: value

services:
    app.kategoria_repository:
        class: AppBundle\Repository\Doctrine\KategoriaRepository
        arguments: ['@doctrine.orm.entity_manager']
    app.wpis_repository:
        class: AppBundle\Repository\Doctrine\WpisRepository
        arguments: ['@doctrine.orm.entity_manager']

    app.default_controller:
        class: AppBundle\Controller\DefaultController
        arguments: ['@app.kategoria_repository', '@app.wpis_repository']

    app.dodaj_kategorie_controller:
        class: AppBundle\Controller\DodajKategorieController
        arguments: ['@app.kategoria_repository']
        calls:
            - [ setContainer, [ '@service_container' ]]

    app.dodaj_wpis_controller:
        class: AppBundle\Controller\DodajWpisController
        arguments: ['@app.kategoria_repository', '@app.wpis_repository']
        calls:
            - [ setContainer, [ '@service_container' ]]

    app.kategorie_controller:
        class: AppBundle\Controller\KategorieController
        arguments: ['@app.kategoria_repository', '@app.wpis_repository']

    app.kontakt_controller:
        class: AppBundle\Controller\KontaktController
        arguments: ['@app.kategoria_repository']
        calls:
            - [ setContainer, [ '@service_container' ]]

    app.login_controller:
        class: AppBundle\Controller\LoginController
        arguments: ['@app.kategoria_repository']
        calls:
            - [ setContainer, [ '@service_container' ]]

    app.security_controller:
        class: AppBundle\Controller\SecurityController
        arguments: ['@app.kategoria_repository']
        calls:
            - [ setContainer, [ '@service_container' ]]
